version: '3.9'

services:
  app:
    build: .
    container_name: bucket_testing_app
    depends_on:
      - database
    env_file:
      - '.env.docker'
    ports:
      - 8080:8080
  database:
    image: 'postgres:11.1-alpine'
    container_name: bucket_testing_db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env.docker'
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: 'redis:7.0'
    container_name: bucket_testing_redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
    command: redis-server --appendonly yes

volumes:
  postgres:
  redis:
